image: java:8-jdk

stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew check
  artifacts:
    paths:
      - firestore-replacement/document-store/build/reports
      - firestore-replacement/relational-store/build/reports

after_script:
  - echo "End CI"
