image: jtwalraven/java-docker-ci:latest

services:
  - docker:dind

stages:
  - build
  - test
  - publish

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export DOCKER_HOST="tcp://localhost:2375"
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

cache:
  paths:
    - .gradle/wrapper
    - document-store/build
    - relational-store/build

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew check
  artifacts:
    when: always
    paths:
      - document-store/build/reports
      - relational-store/build/reports

publish:
  stage: publish
  script:
    - ./gradlew buildDockerImage
    - ./gradlew publishDockerImage
  only:
    - master
