version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: relational_data
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - main

networks:
  main:
